services:
    qimnet.update_tracker.repository:
        class: 'Qimnet\UpdateTrackerBundle\UpdateTracker\Repository'
        private: true
        arguments: 
          - '%qimnet.update_tracker.entity_name%'
          
    qimnet.update_tracker.listener:
        class: 'Qimnet\UpdateTrackerBundle\UpdateTracker\Listener'
        arguments:
            - '@annotation_reader'
            - '@qimnet.update_tracker.repository'
        tags:
            - { name: doctrine.event_subscriber }
            
    qimnet.update_tracker.manager:
        class: 'Qimnet\UpdateTrackerBundle\UpdateTracker\Manager'
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@qimnet.update_tracker.repository'
            
    qimnet.update_tracker.cached_response_factory:
        class: 'Qimnet\UpdateTrackerBundle\Response\CachedResponseFactory'
        arguments:
            - '@qimnet.update_tracker.manager'
            - '%qimnet.update_tracker.default_max_age%'
            - '%qimnet.update_tracker.default_shared_max_age%'